[tool.poetry]
name = "pylibcklb-collection"
version = "0.1.0"
description = ""
authors = ["Tobias Ecklebe <tobias.ecklebe@outlook.de>"]
readme = "README.md"
packages = [{include = "pylibcklb", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
pymongo = "^4.2.0"
pytest = "^7.1.3"


[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
