# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test and Coverage

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - '**/README.md'

permissions:
  contents: read

jobs:
  prepare-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pipx
          pipx install poetry
      - name: Check docker installation
        run: |
          docker --version
      - name: Install the package with poetry
        run: |
          poetry install --all-extras
      - name: Run pytest against the installed package
        run: |
          poetry run coverage run -m pytest && poetry run coverage combine && poetry run coverage report -m